/**
 * @module commands/agent/adhoc/types
 * @description Types for ad-hoc (dynamic) agent generation
 *
 * Ad-hoc agents are generated at runtime by Agent Architect when:
 * - No suitable existing agents are found for a task
 * - Task requires specialized expertise not covered by installed plugins
 * - User requests a "consilium" (multi-agent analysis)
 */

import type { AgentCategory, AgentResult } from '../types';

/**
 * Ad-hoc agent definition generated by Agent Architect
 * These agents exist only in memory for the current session
 */
export interface AdHocAgent {
  /** Unique identifier for this session */
  id: string;
  /** Agent name (e.g., "saas-business-analyst") */
  name: string;
  /** Full system prompt for the agent */
  prompt: string;
  /** Short description of what this agent does */
  description: string;
  /** Primary focus area */
  focus: string;
  /** Expertise domains */
  expertise: string[];
  /** Agent archetype */
  archetype: AdHocAgentArchetype;
  /** Execution priority (1 = first) */
  priority: number;
  /** Can run in parallel with other agents */
  parallel: boolean;
  /** Model to use (defaults to inherit from parent) */
  model?: 'sonnet' | 'opus' | 'haiku' | 'inherit';
}

/**
 * Agent archetypes from Agent Architect design
 */
export type AdHocAgentArchetype =
  | 'specialist' // Deep domain expertise
  | 'assistant' // Broad task support
  | 'creator' // Content/artifact generation
  | 'analyzer' // Data/code analysis
  | 'orchestrator'; // Workflow coordination

/**
 * Request to generate ad-hoc agents
 */
export interface AdHocGenerationRequest {
  /** Original user task */
  task: string;
  /** Context about the project/domain */
  context?: string;
  /** Specific focus areas requested */
  focusAreas?: string[];
  /** Maximum agents to generate */
  maxAgents?: number;
  /** Prefer parallel execution */
  preferParallel?: boolean;
  /** Project root for context gathering */
  projectRoot?: string;
}

/**
 * Response from Agent Architect with generated agents
 */
export interface AdHocGenerationResponse {
  /** Generated ad-hoc agents */
  agents: AdHocAgent[];
  /** Recommended execution strategy */
  executionStrategy: 'sequential' | 'parallel' | 'mixed';
  /** Prompt for synthesizing results from all agents */
  synthesisPrompt: string;
  /** Reasoning behind agent selection */
  reasoning: string;
  /** Generation duration in ms */
  durationMs: number;
}

/**
 * Ad-hoc agent execution result
 */
export interface AdHocAgentResult extends AgentResult {
  /** Reference to the ad-hoc agent definition */
  adHocAgent: AdHocAgent;
  /** Quality score (0-100) based on task completion */
  qualityScore?: number;
  /** Whether to recommend saving this agent as a plugin */
  recommendSave?: boolean;
}

/**
 * Consolidated result from multiple ad-hoc agents
 */
export interface AdHocConsiliumResult {
  /** Original task */
  task: string;
  /** All agent results */
  agentResults: AdHocAgentResult[];
  /** Synthesized conclusion from all agents */
  synthesis: string;
  /** Agents that performed well (qualityScore >= 80) */
  highPerformers: AdHocAgent[];
  /** Total execution time */
  totalDurationMs: number;
  /** Execution strategy used */
  strategy: 'sequential' | 'parallel' | 'mixed';
}

/**
 * Options for saving an ad-hoc agent as a permanent plugin
 */
export interface SaveAdHocAgentOptions {
  /** Agent to save */
  agent: AdHocAgent;
  /** Target plugin name (new or existing) */
  pluginName: string;
  /** Category for the agent */
  category: AgentCategory;
  /** Optional skills to generate */
  generateSkills?: boolean;
  /** Custom file path (defaults to standard plugin structure) */
  customPath?: string;
}

/**
 * Result of saving an ad-hoc agent
 */
export interface SaveAdHocAgentResult {
  success: boolean;
  /** Path where the agent was saved */
  filePath: string;
  /** Plugin name */
  pluginName: string;
  /** Any warnings during save */
  warnings?: string[];
}
