# GitHub Secret Scanning Configuration
#
# This project contains a security secrets detector (krolik audit).
# Test files intentionally contain secret-like patterns for testing detection.
# These are NOT real secrets - they are test fixtures.
#
# See: https://docs.github.com/en/code-security/secret-scanning/push-protection

paths-ignore:
  # Test files with intentional secret patterns for detector testing
  - 'tests/**/*.test.ts'
  - 'tests/**/*.spec.ts'
  - 'tests/fixtures/**'
  # Security detector source (contains pattern definitions)
  - 'src/lib/@swc/detectors/secrets/**'
