/**
 * @module mcp/tools
 * @description AUTO-GENERATED tool imports - DO NOT EDIT MANUALLY
 *
 * This file is auto-generated by scripts/generate-tool-imports.ts
 * Run: pnpm generate:tools
 *
 * Adding a new tool:
 * 1. Create src/mcp/tools/my-tool.ts
 * 2. Export MCPToolDefinition and call registerTool()
 * 3. Run: pnpm generate:tools (or it runs automatically on build)
 * 4. That's it! No manual imports needed.
 */

// Auto-discovered tool imports
// Each tool file calls registerTool() on import
import './audit';
import './context';
import './fix';
import './flag-builder';
import './issue';
import './refactor';
import './review';
import './routes';
import './schema';
import './status';

// Re-export registry functions
export {
  buildHandlerRegistry,
  getAllTools,
  getToolDefinitions,
  getToolNames,
  isValidTool,
  runTool,
} from './registry';

// Type exports
export type { MCPTool, MCPToolDefinition, SchemaProperty, ToolHandler } from './types';

// Legacy compatibility: export ALL_TOOLS constant
// This maintains backward compatibility with existing code
import { getAllTools } from './registry';
export const ALL_TOOLS = getAllTools();
