/**
 * @module commands/context/formatters/text
 * @description Text, JSON, and Markdown formatters for context output
 */

import {
  blockquote,
  bulletList,
  formatJson as formatJsonBase,
  heading,
  horizontalRule,
  inlineCode,
} from '@/lib/@format';
import type { ContextResult, Logger } from '../../../types';

const MAX_BODY_LENGTH = 500;

/**
 * Print context to console
 */
export function printContext(context: ContextResult, logger: Logger, verbose = false): void {
  logger.section('Task Context');

  console.log(`\x1b[1m${context.task}\x1b[0m`);

  if (context.issue) {
    console.log('');
    console.log(`\x1b[2mIssue #${context.issue.number}: ${context.issue.title}\x1b[0m`);
    if (verbose && context.issue.body) {
      const body =
        context.issue.body.length > MAX_BODY_LENGTH
          ? `${context.issue.body.slice(0, MAX_BODY_LENGTH)}...`
          : context.issue.body;
      console.log(body);
    }
  }

  console.log('');
  logger.info('Detected Domains:');
  for (const domain of context.domains) {
    console.log(`  \x1b[33m${domain}\x1b[0m`);
  }

  console.log('');
  logger.info('Related Files:');
  for (const file of context.relatedFiles) {
    console.log(`  \x1b[36m${file}\x1b[0m`);
  }

  console.log('');
  logger.info('Suggested Approach:');
  for (const step of context.approach) {
    console.log(`  ${step}`);
  }

  console.log('');
}

/**
 * Format context as JSON
 */
export function formatJson(context: ContextResult): string {
  return formatJsonBase(context);
}

/**
 * Format context as markdown
 */
export function formatMarkdown(context: ContextResult): string {
  const lines: string[] = [heading(`Task Context: ${context.task}`, 1), ''];

  if (context.issue) {
    lines.push(blockquote(`Issue #${context.issue.number}: ${context.issue.title}`));
    lines.push('');
  }

  lines.push(heading('Detected Domains', 2));
  lines.push('');
  lines.push(bulletList(context.domains));
  lines.push('');

  lines.push(heading('Related Files', 2));
  lines.push('');
  lines.push(bulletList(context.relatedFiles.map((file) => inlineCode(file))));
  lines.push('');

  lines.push(heading('Suggested Approach', 2));
  lines.push('');
  lines.push(bulletList(context.approach));
  lines.push('');

  lines.push(horizontalRule());
  lines.push('');
  lines.push('*Generated by krolik-cli*');

  return lines.join('\n');
}
