/**
 * @module commands/context/formatters/text
 * @description Text, JSON, and Markdown formatters for context output
 */

import type { Logger, ContextResult } from "../../../types";

const MAX_BODY_LENGTH = 500;

/**
 * Print context to console
 */
export function printContext(
  context: ContextResult,
  logger: Logger,
  verbose = false,
): void {
  logger.section("Task Context");

  console.log(`\x1b[1m${context.task}\x1b[0m`);

  if (context.issue) {
    console.log("");
    console.log(
      `\x1b[2mIssue #${context.issue.number}: ${context.issue.title}\x1b[0m`,
    );
    if (verbose && context.issue.body) {
      const body =
        context.issue.body.length > MAX_BODY_LENGTH
          ? context.issue.body.slice(0, MAX_BODY_LENGTH) + "..."
          : context.issue.body;
      console.log(body);
    }
  }

  console.log("");
  logger.info("Detected Domains:");
  for (const domain of context.domains) {
    console.log(`  \x1b[33m${domain}\x1b[0m`);
  }

  console.log("");
  logger.info("Related Files:");
  for (const file of context.relatedFiles) {
    console.log(`  \x1b[36m${file}\x1b[0m`);
  }

  console.log("");
  logger.info("Suggested Approach:");
  for (const step of context.approach) {
    console.log(`  ${step}`);
  }

  console.log("");
}

/**
 * Format context as JSON
 */
export function formatJson(context: ContextResult): string {
  return JSON.stringify(context, null, 2);
}

/**
 * Format context as markdown
 */
export function formatMarkdown(context: ContextResult): string {
  const lines: string[] = [`# Task Context: ${context.task}`, ""];

  if (context.issue) {
    lines.push(`> Issue #${context.issue.number}: ${context.issue.title}`);
    lines.push("");
  }

  lines.push("## Detected Domains");
  lines.push("");
  for (const domain of context.domains) {
    lines.push(`- ${domain}`);
  }
  lines.push("");

  lines.push("## Related Files");
  lines.push("");
  for (const file of context.relatedFiles) {
    lines.push(`- \`${file}\``);
  }
  lines.push("");

  lines.push("## Suggested Approach");
  lines.push("");
  for (const step of context.approach) {
    lines.push(`- ${step}`);
  }
  lines.push("");

  lines.push("---");
  lines.push("");
  lines.push("*Generated by krolik-cli*");

  return lines.join("\n");
}
